# Generated by Django 4.2.20 on 2025-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('parent_mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('aadhar', models.CharField(max_length=12)),
                ('aadhar_image', models.FileField(upload_to='aadhar/')),
                ('profile_image', models.FileField(default='profile/default.jpg', upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
