# Generated by Django 4.2.20 on 2025-03-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
