# Generated by Django 4.2.20 on 2025-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_qr',
            field=models.FileField(default='profile_qr/default.jpg', upload_to='profile_qr/'),
        ),
    ]
