# Generated by Django 4.2.20 on 2025-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_profile_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_image',
            field=models.FileField(blank=True, null=True, upload_to='aadhar/'),
        ),
    ]
