# Generated by Django 4.2.20 on 2025-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_profile_image_alter_student_profile_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
