# Generated by Django 4.2.20 on 2025-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image_verified',
            field=models.BooleanField(default=False),
        ),
    ]
