# Generated by Django 4.2.20 on 2025-03-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_aadhar_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_status',
            field=models.BooleanField(default=False),
        ),
    ]
