# Generated by Django 4.2.20 on 2025-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_batch_end_date_student_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_name',
            field=models.CharField(blank=True, default='General', max_length=30, null=True),
        ),
    ]
