# Generated by Django 4.2.20 on 2025-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='aadhar_image',
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
