# Generated by Django 4.2.20 on 2025-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_student_aadhar_image_alter_student_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
    ]
