# Generated by Django 4.2.20 on 2025-03-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_verified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
