# Generated by Django 4.2.20 on 2025-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_student_aadhar_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_marker',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
