# Generated by Django 4.2.20 on 2025-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_fees_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
