# Generated by Django 4.2.20 on 2025-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_event_studentfeedback_cricket_team_cricket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
